Completed javascript-light-bulb challenge. -Brandon Moy
brandon-moy/c0822-code-solutions pull request #47
Opened 2022-09-06 23:18 UTC by brandon-moy

https://user-images.githubusercontent.com/109567499/188756494-8e6370bc-5b9e-4638-a7f7-ee1a1b14290b.mp4

2022-09-06 23:23 UTC, codingcodymiller requested changes

2022-09-06 23:23 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if ($background.className === 'light') {
By doing this, your logic is dependent on the current state of the DOM, which is not ideal. Instead, I would create a variable to keep track of if the light is currently on or not, and use that variable's value to determine what action to take when the light is clicked.

2022-09-06 23:27 UTC, brandon-moy commented on javascript-light-bulb/main.js
> +  if ($background.className === 'light') {
Thanks Cody, that makes sense. Would using a variable like this work and having it set as 'on' since the page will load with the light on and there use that variable to determine whether the light should go on or off?
![image](https://user-images.githubusercontent.com/109567499/188757358-a29177cb-848d-4ab7-aba0-a77cd718f6f8.png)

https://user-images.githubusercontent.com/109567499/188757371-7b1869fe-99a2-47d0-ab37-8dbaa24e7f31.mp4

2022-09-07 16:15 UTC, codingcodymiller requested changes

2022-09-07 16:15 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +var light = 'on';
Instead of using `"on"` and `"off"`, just use `true` and `false` 🤓

2022-09-07 16:50 UTC, brandon-moy commented on javascript-light-bulb/main.js
> +var light = 'on';
Got it. Probably should have thought of that in the first place. Changes have been made, thanks!
![image](https://user-images.githubusercontent.com/109567499/188935132-6edd4f62-4ec9-45fe-abf9-3ac1770f4d90.png)

2022-09-07 16:53 UTC, codingcodymiller approved these changes

2022-09-07 16:53 UTC, merged