Completed javascript-carousel challenge. -Brandon Moy
brandon-moy/c0822-code-solutions pull request #67
Opened 2022-09-20 19:31 UTC by brandon-moy

Carousel Initial Loop Demo

[carousel initial loop demo.webm](https://user-images.githubusercontent.com/109567499/191347522-2e3db38f-d693-4bad-97a2-25db2c3bdaa0.webm)

Left and Right Arrow Demo (pauses between clicks to help show restart of timer)

[left and right arrow demo.webm](https://user-images.githubusercontent.com/109567499/191347548-a87b3d7d-a9d7-4ad5-bcc4-6f09220c52a6.webm)

Buttons Demo (pauses between clicks to help show restart of timer)

[button demo.webm](https://user-images.githubusercontent.com/109567499/191347567-5f5b4c62-5032-47b4-93cb-3a326cf35a34.webm)

2022-09-20 21:02 UTC, codingcodymiller requested changes

2022-09-20 21:02 UTC, codingcodymiller commented on javascript-carousel/main.js
> +      $icons[j].classList.add('fa-solid');
Instead of doing this conditional, I would just make all of them hidden and all dots hollow, then make the image at `imgPosition` visible and the dot at `imgPosition` solid

2022-09-20 21:02 UTC, codingcodymiller commented on javascript-carousel/main.js
> +    } else {
Instead of doing this conditional, I would just make all of them hidden and all dots hollow, then make the image at `imgPosition - 1` visible and the dot at `imgPosition - 1` solid

2022-09-20 21:02 UTC, codingcodymiller commented on javascript-carousel/main.js
> +      $icons[k].classList.add('fa-solid');
Instead of doing this conditional, I would just make all of them hidden and all dots hollow, then make the image at `imgPosition` visible and the dot at `imgPosition` solid

2022-09-20 21:23 UTC, brandon-moy commented on javascript-carousel/main.js
> +      $icons[j].classList.add('fa-solid');
Gotcha, I switched over the code to be like this and used my loop to hide all the images and hollow the buttons and then pulled my items at the `imgPosition` to know what to adjust. 

![image](https://user-images.githubusercontent.com/109567499/191367136-643d3994-4aa7-4f2a-a746-dfe6fe7760cb.png)

2022-09-20 21:23 UTC, brandon-moy commented on javascript-carousel/main.js
> +    } else {
Same adjusted made here as above.

![image](https://user-images.githubusercontent.com/109567499/191367255-db3ce37f-1277-408b-ae7e-419f05affbb5.png)

2022-09-20 21:24 UTC, brandon-moy commented on javascript-carousel/main.js
> +      $icons[k].classList.add('fa-solid');
Same adjusted as above made here. Also changed my loop to use var `l` for personal preference of different variable letters in different functions/loops.

![image](https://user-images.githubusercontent.com/109567499/191367488-f8cc6e2f-5f7c-4685-b099-b988911130ed.png)

2022-10-09 19:47 UTC, thebearingedge approved these changes

2022-10-10 17:46 UTC, merged